name: podcast_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  animate_do: ^3.0.2
  bloc: ^8.1.0
  connectivity_plus: ^3.0.2
  equatable: ^2.0.5
  flow_builder: ^0.0.9
  flutter_bloc: ^8.1.1
  http: ^0.13.5
  iconsax: ^0.0.8
  intl: ^0.18.0
  oxidized: ^5.3.0
  get_storage: ^2.0.3
  audioplayers: ^2.0.0
  animations: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/logos/
